description: "Checks for Git changes since the last nightly CI job (24 hrs)"
name: "Nightly Check"
outputs: 
  changes: 
    description: "True if changes have been made in the past 24 hrs, otherwise false"
    value: "${{ steps.check-changes.outputs.changes }}"
runs: 
  steps: 
    - 
      uses: actions/checkout@v2
    - 
      continue-on-error: true
      id: check-changes
      name: "check if latest commit is within 24 hrs"
      run: "test -z $(git rev-list --after=\"24 hours\" ${{ github.sha }}) && echo \"::set-output name=changes::true\""
  using: composite
