author: "Luke Carr"
branding:
  icon: moon
  color: gray-dark
description: "Checks for Git changes since the last nightly CI job (24 hrs)"
name: "Nightly Check"
inputs:
  within:
    description: "The duration to look back at for changes, defaults to '24 hrs'"
    required: false
    default: "24 hrs"
outputs: 
  changes: 
    description: "True if changes have been made in the past 24 hrs (or the \"within\" input if provided), otherwise false"
    value: "${{ steps.check-changes.outputs.changes }}"
runs: 
  steps: 
    - 
      uses: actions/checkout@v4
    - 
      continue-on-error: true
      shell: bash
      id: check-changes
      name: "check if latest commit is within 24 hrs"
      run: "test -z $(git rev-list --after=\"${{ github.event.inputs.within }}\" ${{ github.sha }}) && echo \"changes=true\" >> $GITHUB_OUTPUT"
  using: composite
